# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'giris.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(250, 377)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(30, 10, 191, 251))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.adLine = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.adLine.setFont(font)
        self.adLine.setObjectName("adLine")
        self.verticalLayout.addWidget(self.adLine)
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.sifreLine = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.sifreLine.setFont(font)
        self.sifreLine.setObjectName("sifreLine")
        self.verticalLayout.addWidget(self.sifreLine)
        spacerItem = QtWidgets.QSpacerItem(20, 30, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem)
        self.girisButon = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.girisButon.setFont(font)
        self.girisButon.setObjectName("girisButon")
        self.verticalLayout.addWidget(self.girisButon)
        self.kayitButon = QtWidgets.QPushButton(self.centralwidget)
        self.kayitButon.setGeometry(QtCore.QRect(90, 300, 75, 23))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.kayitButon.setFont(font)
        self.kayitButon.setObjectName("kayitButon")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 250, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.applyStyles()

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Giriş Ekranı"))
        self.label_3.setText(_translate("MainWindow", "Giriş Yap"))
        self.label.setText(_translate("MainWindow", "Kullanıcı Adı"))
        self.label_2.setText(_translate("MainWindow", "Şifre"))
        self.girisButon.setText(_translate("MainWindow", "Giriş"))
        self.kayitButon.setText(_translate("MainWindow", "Kayıt Ol"))

    def applyStyles(self):
        # Ana pencereye stil uygula
        style = """
            background-color: #f0f0f0;
            font-family: Arial;
        """
        self.centralwidget.setStyleSheet(style)

        # Label stili
        label_style = """
            font-family: Arial;
            font-size: 16px;
            color: #333333;
        """
        self.label_3.setStyleSheet(label_style)

        # Buton stili
        button_style = """
            QPushButton {
                background-color: #4CAF50; /* Yeşil */
                border: none;
                color: white;
                padding: 10px 24px;
                text-align: center;
                text-decoration: none;
                font-size: 16px;
                border-radius: 8px;
            }

            QPushButton:hover {
                background-color: #45a049; /* Koyu yeşil */
            }

            QPushButton:pressed {
                background-color: #3e8e41; /* Daha koyu yeşil */
            }
            """
        self.girisButon.setStyleSheet(button_style)