# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'liste.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(721, 454)
        self.tablo = QtWidgets.QTableWidget(Form)
        self.tablo.setGeometry(QtCore.QRect(0, 0, 851, 451))
        self.tablo.setObjectName("tablo")
        self.tablo.setColumnCount(8)
        self.tablo.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tablo.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablo.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablo.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablo.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablo.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablo.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablo.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablo.setHorizontalHeaderItem(7, item)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Seyahat Listesi"))
        item = self.tablo.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Başlangıç"))
        item = self.tablo.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Varış"))
        item = self.tablo.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Mesafe"))
        item = self.tablo.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Araçla Varış"))
        item = self.tablo.horizontalHeaderItem(4)
        item.setText(_translate("Form", "Uçakla Varış"))
        item = self.tablo.horizontalHeaderItem(5)
        item.setText(_translate("Form", "Otel"))
        item = self.tablo.horizontalHeaderItem(6)
        item.setText(_translate("Form", "Otel Puanı"))
        item = self.tablo.horizontalHeaderItem(7)
        item.setText(_translate("Form", "Fiyat"))
